services:
  - type: web
    name: yalo-transcriber
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: starter
    envVars:
      - key: OPENAI_API_KEY
        sync: false